[package]
name = "scryptenc-cli"
version = "0.4.1"
authors = ["Shun Sakai <sorairolake@protonmail.ch>"]
edition = "2021"
rust-version = "1.64.0"
description = "An utility for encrypt and decrypt files"
readme = "README.md"
repository = "https://github.com/sorairolake/rscrypt"
license = "GPL-3.0-or-later"
keywords = ["scrypt"]
categories = ["command-line-utilities"]
exclude = [
  "/.github",
  "/*.json",
  "/clippy.toml",
  "/Cross.toml",
  "/doc",
  "/justfile",
  "/rustfmt.toml",
  "/tests",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rscrypt"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.70"
byte-unit = "4.0.19"
ciborium = { version = "0.2.0", optional = true }
clap = { version = "4.1.14", features = ["derive", "wrap_help"] }
clap_complete = "4.2.0"
dialoguer = { version = "0.10.3", default-features = false, features = ["password"] }
fraction = { version = "0.13.1", default-features = false }
humantime = "2.1.0"
once_cell = "1.17.1"
rmp-serde = { version = "1.1.1", optional = true }
scryptenc = "0.5.0"
serde = { version = "1.0.159", features = ["derive"], optional = true }
serde_json = { version = "1.0.95", optional = true }
serde_yaml = { version = "0.9.19", optional = true }
sysexits = "0.5.0"
sysinfo = "0.28.4"
thiserror = "1.0.40"
toml = { version = "0.7.3", optional = true }

[dev-dependencies]
assert_cmd = "2.0.10"
predicates = "3.0.2"

[features]
default = ["cbor", "json", "msgpack", "toml", "yaml"]
cbor = ["dep:ciborium", "dep:serde"]
json = ["dep:serde", "dep:serde_json"]
msgpack = ["dep:rmp-serde", "dep:serde"]
toml = ["dep:serde", "dep:toml"]
yaml = ["dep:serde", "dep:serde_yaml"]

[profile.release]
lto = true
strip = true
