[package]
name = "scryptenc-cli"
version = "0.1.0"
authors = ["Shun Sakai <sorairolake@protonmail.ch>"]
edition = "2021"
rust-version = "1.61.0"
description = "An utility for encrypt and decrypt files"
readme = "README.md"
repository = "https://github.com/sorairolake/rscrypt"
license = "GPL-3.0-or-later"
keywords = ["scrypt"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rscrypt"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.66"
byte-unit = { version = "4.0.17", default-features = false, features = ["alloc", "u128"] }
clap = { version = "4.0.26", features = ["derive", "wrap_help"] }
clap_complete = "4.0.5"
dialoguer = { version = "0.10.2", default-features = false, features = ["password"] }
scryptenc = "0.4.1"
sysexits = "0.3.4"

[dev-dependencies]
assert_cmd = "2.0.6"
predicates = "2.1.3"

[profile.release]
lto = true
strip = true
