[package]
name = "scryptenc-cli"
version = "0.1.1"
authors = ["Shun Sakai <sorairolake@protonmail.ch>"]
edition = "2021"
rust-version = "1.61.0"
description = "An utility for encrypt and decrypt files"
readme = "README.md"
repository = "https://github.com/sorairolake/rscrypt"
license = "GPL-3.0-or-later"
keywords = ["scrypt"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rscrypt"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.66"
byte-unit = "4.0.17"
clap = { version = "4.0.29", features = ["derive", "wrap_help"] }
clap_complete = "4.0.6"
dialoguer = { version = "0.10.2", default-features = false, features = ["password"] }
fraction = { version = "0.12.1", default-features = false }
once_cell = "1.16.0"
scryptenc = "0.4.1"
sysexits = "0.3.4"
sysinfo = "0.26.8"
thiserror = "1.0.37"

[dev-dependencies]
assert_cmd = "2.0.7"
predicates = "2.1.3"

[profile.release]
lto = true
strip = true
