# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: REUSE Compliance Check

on:
  push:
    branches:
      - 'develop'
      - 'master'
  pull_request:

jobs:
  reuse:
    name: REUSE
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v2.0.0
